#!/usr/bin/env bash

test "$#" != 1 && {
   echo "Usage: $0 <gh repo>"
   exit 1
} 

git clone --depth 1 "$1" temp-linecount-repo &&
  printf "('temp-linecount-repo' will be deleted automatically)\n\n\n" &&
  cloc temp-linecount-repo &&
  rm -rf temp-linecount-repo

